name: 1 - [TERRATEST] Running Terratest

on: push

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  TF_VAR_aws_key_pub: ${{secrets.TF_VAR_aws_key_pub}}

jobs:
  terratest:
    name: Terratest
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.6'
      
      - name: Setup Go
        run: |
          export PATH=$PATH:/usr/bin/
          cd tests
          go mod download
          go install github.com/gruntwork-io/terratest/modules/terraform
          go install github.com/stretchr/testify/assert
          cd /usr/bin/
          go install github.com/jstemmer/go-junit-report/v2@latest
          
      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE/tests
          go test -v -timeout 30m | go-junit-report -out reports/report_junit.xml
          ls reports/
          
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: reports/report_junit.xml