name: 1 - [TERRATEST] Running Terratest

on: push

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  TF_VAR_aws_key_pub: ${{secrets.TF_VAR_aws_key_pub}}

jobs:
  terratest:
    name: Terratest
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.6'
          
      - run: echo "Setting up Go environment..."
      - run: go version
      - run: cd tests
      - run: go mod init terratest
      - run: go mod tidy
      - run: go get -u github.com/gruntwork-io/terratest/modules/terraform
      - run: go get -u github.com/stretchr/testify/assert
      - run: cd /usr/bin/
      - run: go get -u github.com/jstemmer/go-junit-report
      - run: go get -u github.com/jstemmer/go-junit-report
      - run: echo $GITHUB_WORKSPACE
      - run: cd $GITHUB_WORKSPACE
      - run: cd tests
      # - run: echo "Setting up Terraform environment..."
      # - run: sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
      # - run: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      # - run: gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
      # - run: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      # - run: sudo apt update
      - run: terraform version
      - run: echo "Running Terratest..."
      - run: go test -v -timeout 30m | go-junit-report -out reports/report_junit.xml
      